# Generated by Django 3.1.7 on 2021-08-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210831_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='author',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='recommend',
            name='seller_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='recommend',
            name='title',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
