# Generated by Django 3.1.7 on 2021-08-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210831_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='medium',
            field=models.CharField(choices=[('PAPERBACK', 'paperback'), ('ELECTRONIC', 'electronic')], default='PAPERBACK', max_length=200),
        ),
        migrations.AddField(
            model_name='recommend',
            name='price',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
